server:
  port: 8888

treasury:
  kafka:
    consumer-enabled: true

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 30000
            loggerLevel: FULL
    stream:
      function:
        definition: kafkaConsumer;
      bindings:
        kafkaProducer-out-0:
          destination: out
          binder: kafka
        #В качестве примера
        kafkaConsumer-in-0:
          destination: in
          binder: kafka
          consumer:
            backOffInitialInterval: 60000
            backOffMaxInterval: 3840000
            max-attempts: 8
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: kafka
                      defaultBrokerPort: 9092
                      minPartitionCount: 3
                      configuration:
                        security:
                          protocol: PLAINTEXT
                        sasl:
                          mechanism: PLAIN
                      jaas:
                        loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
                        options:
                          username: test
                          password: test
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://db:5432/asset
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

feign:
  url:
    alpha: https://www.alphavantage.co
    rates: https://openexchangerates.org
    local: http://localhost:8080
  path: api/asset

stock:
  apiKey: 7K787PFK934JZ63F
  function: GLOBAL_QUOTE
  appId: 17bdd6eccfa44586a9ef23c296e5b0de
  base: USD