server:
  port: 8888

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/asset
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 30000
            loggerLevel: FULL

feign:
  url:
    alpha: https://www.alphavantage.co
    rates: https://openexchangerates.org
    local: http://localhost:8080
  path: api/asset

stock:
  apiKey: 7K787PFK934JZ63F
  function: GLOBAL_QUOTE
  appId: 17bdd6eccfa44586a9ef23c296e5b0de
  base: USD
